/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business;

import Persistence.Collaborates;
import Persistence.conexionOracle;
import Persistence.CaseManager;
import Persistence.CollaboratesManager;
import Persistence.ExpertManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jesus
 */
public class CollaboratesWindow extends javax.swing.JFrame {

    private CollaboratesManager mCol=null;
    
    DefaultTableModel modeloTColabora = new DefaultTableModel() {

    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
    public CollaboratesWindow(conexionOracle co) throws SQLException {
        mCol = new CollaboratesManager(co);
        initComponents();
        DibujarTablaColabora();
        pideColaborador();
    }

    private CollaboratesWindow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    private void DibujarTablaColabora() {
        tColabora.setModel(modeloTColabora);
        String[] columnasTabla = {"Id","Name","Speciality","Description"};
        modeloTColabora.setColumnIdentifiers(columnasTabla);
        // Para no permitir el redimensionamiento de las columnas con el ratón
        tColabora.getTableHeader().setResizingAllowed(false);
        // Así se fija el ancho de las columnas
        tColabora.getColumnModel().getColumn(0).setPreferredWidth(25);
        tColabora.getColumnModel().getColumn(1).setPreferredWidth(140);
        tColabora.getColumnModel().getColumn(2).setPreferredWidth(80);
        tColabora.getColumnModel().getColumn(3).setPreferredWidth(122);
}
    
private void rellenarTablaColabora (ResultSet rs) {
    Object[] columna = new Object[5];
        try {
            while(rs.next()) 
            { 
                columna[0] = rs.getString("CODEXPERT");
                columna[1] = rs.getString("NAME");
                columna[2] = rs.getString("SPECIALISM");
                columna[3] = rs.getString("DESCRIPCION");
                modeloTColabora.addRow(columna);
            }   } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error at refilling the tables: "+ex.getMessage());
        }
}



private void vaciarTablaColabora(){
    int i = modeloTColabora.getRowCount();
    while (modeloTColabora.getRowCount() > 0)
    modeloTColabora.removeRow(0);
}
    

private void pideColaborador() throws SQLException 
{
    String colaboradorSeleccionado = txtColaborador.getText();
    ResultSet rs=mCol.listaColaboradoresPorCaso(colaboradorSeleccionado);
    rellenarTablaColabora (rs);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabla = new javax.swing.JScrollPane();
        tColabora = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtColaborador = new javax.swing.JTextField();
        btmShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tColabora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setViewportView(tColabora);

        jLabel1.setText("Insert the Code of a Case");

        txtColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColaboradorActionPerformed(evt);
            }
        });

        btmShow.setText("Show");
        btmShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btmShow)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmShow))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmShowActionPerformed
        // TODO add your handling code here:
        vaciarTablaColabora();
        try {
            pideColaborador();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error at Show: "+ ex.getMessage());
        }
    }//GEN-LAST:event_btmShowActionPerformed

    private void txtColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColaboradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollaboratesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollaboratesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollaboratesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollaboratesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollaboratesWindow().setVisible(true);
               // new ventanaColaboraciones().dispose();
                //new ventanaColaboraciones().dispose();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Tabla;
    private javax.swing.JButton btmShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tColabora;
    private javax.swing.JTextField txtColaborador;
    // End of variables declaration//GEN-END:variables
}
