/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business;

//import static Aplicacion.aplicacionCliente.co;
import Persistence.conexionOracle;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class MainWindow extends javax.swing.JFrame {

        static conexionOracle co = null;
    /**
     * Creates new form ClienteFrame
     */
    public MainWindow() {
        
            try {
                co=new conexionOracle();
                initComponents();
            } catch (Exception ex) {
                //Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error on main Window...: "+ex.getMessage());
                System.exit(1);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenuPrincipal = new javax.swing.JMenuBar();
        Conexion = new javax.swing.JMenu();
        SubMenuConectionDisconect = new javax.swing.JMenuItem();
        SubMenuConectionConect = new javax.swing.JMenuItem();
        SubMenuConectionExit = new javax.swing.JMenuItem();
        Expertos = new javax.swing.JMenu();
        SubMenuExpertExpertManagement = new javax.swing.JMenuItem();
        PolicialCases = new javax.swing.JMenu();
        Colaboraciones = new javax.swing.JMenu();
        SubMenuColaboracionesBuscarColaboraciones1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarraMenuPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BarraMenuPrincipal.setForeground(new java.awt.Color(255, 102, 102));

        Conexion.setBorder(null);
        Conexion.setText("Conect");

        SubMenuConectionDisconect.setText("Disconect");
        SubMenuConectionDisconect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuConectionDisconectActionPerformed(evt);
            }
        });
        Conexion.add(SubMenuConectionDisconect);

        SubMenuConectionConect.setText("Conect");
        SubMenuConectionConect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuConectionConectActionPerformed(evt);
            }
        });
        Conexion.add(SubMenuConectionConect);

        SubMenuConectionExit.setText("Exit");
        SubMenuConectionExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuConectionExitActionPerformed(evt);
            }
        });
        Conexion.add(SubMenuConectionExit);

        BarraMenuPrincipal.add(Conexion);

        Expertos.setText("Expert");

        SubMenuExpertExpertManagement.setText("Expert Management");
        SubMenuExpertExpertManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuExpertExpertManagementActionPerformed(evt);
            }
        });
        Expertos.add(SubMenuExpertExpertManagement);

        BarraMenuPrincipal.add(Expertos);

        PolicialCases.setText("Cases");
        BarraMenuPrincipal.add(PolicialCases);

        Colaboraciones.setText("Colaborations");

        SubMenuColaboracionesBuscarColaboraciones1.setText("Search Colaborator");
        SubMenuColaboracionesBuscarColaboraciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuColaboracionesBuscarColaboraciones1ActionPerformed(evt);
            }
        });
        Colaboraciones.add(SubMenuColaboracionesBuscarColaboraciones1);

        BarraMenuPrincipal.add(Colaboraciones);

        setJMenuBar(BarraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenuConectionDisconectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuConectionDisconectActionPerformed
        // TODO add your handling code here:
        
        try {
         co.desconexion();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } finally {
//            this.setVisible(false);//close the window
//            this.dispose();//free resourcess(libero los recursos)
        }
        
    }//GEN-LAST:event_SubMenuConectionDisconectActionPerformed

    private void SubMenuExpertExpertManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuExpertExpertManagementActionPerformed
        // TODO add your handling code here:
        
        try {
            ExpertWindow vE = new ExpertWindow(co);
            vE.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_SubMenuExpertExpertManagementActionPerformed

    private void SubMenuColaboracionesBuscarColaboraciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuColaboracionesBuscarColaboraciones1ActionPerformed
        // TODO add your handling code here:
         try {
            CollaboratesWindow vC = new CollaboratesWindow(co);
            vC.setVisible(true);
            //TODO: CHeck that can load from db
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_SubMenuColaboracionesBuscarColaboraciones1ActionPerformed

    private void SubMenuConectionConectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuConectionConectActionPerformed
        // TODO add your handling code here:
         try {
                co=new conexionOracle();
                initComponents();
            } catch (Exception ex) {
                //Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error on main Window...: "+ex.getMessage());
                System.exit(1);
            }
    }//GEN-LAST:event_SubMenuConectionConectActionPerformed

    private void SubMenuConectionExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuConectionExitActionPerformed
        // TODO add your handling code here:
          try {
         co.desconexion();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } finally {
            this.setVisible(false);//close the window
            this.dispose();//free resourcess(libero los recursos)
        }
    }//GEN-LAST:event_SubMenuConectionExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenuPrincipal;
    private javax.swing.JMenu Colaboraciones;
    private javax.swing.JMenu Conexion;
    private javax.swing.JMenu Expertos;
    private javax.swing.JMenu PolicialCases;
    private javax.swing.JMenuItem SubMenuColaboracionesBuscarColaboraciones1;
    private javax.swing.JMenuItem SubMenuConectionConect;
    private javax.swing.JMenuItem SubMenuConectionDisconect;
    private javax.swing.JMenuItem SubMenuConectionExit;
    private javax.swing.JMenuItem SubMenuExpertExpertManagement;
    // End of variables declaration//GEN-END:variables
}
