/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business;

import Persistence.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.*;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class ExpertFrame extends javax.swing.JFrame {

    /**
     * Creates new form ExpertFrame
     */
    //Declaration of variables 
    ExpertManager Exp = null;
    OracleConnection co = null;

    DefaultTableModel TExpertLook = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    public ExpertFrame() {

        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**/

    /**
     * Constructor del Frame Expertos
     * @param co
     * @throws java.sql.SQLException
     */

    public ExpertFrame(OracleConnection co) throws SQLException {

        Exp = new ExpertManager(co);
        initComponents();
        drawExpertTable();
        viewExperts();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    private void deleteExpertTable() {

        while (TExpertLook.getRowCount() > 0) {
            TExpertLook.removeRow(0);
        }
    }

    
    
    private void fillExpTable(ArrayList<Expert> expertos) {

        Object[] column = new Object[5];
        int numRegistros = expertos.size();
        for (int i = 0; i < numRegistros; i++) {
            column[0] = expertos.get(i).getCodEXPERT();
            column[1] = expertos.get(i).getName();
            column[2] = expertos.get(i).getCountry();
            column[3] = expertos.get(i).getSex();
            column[4] = expertos.get(i).getSpecialism();
            TExpertLook.addRow(column);
        }
    }

    private void drawExpertTable() {

        ExpTable.setModel(TExpertLook);
        String[] columns = {"Code", "Name", "Country", "Sex", "Specialism"};
        TExpertLook.setColumnIdentifiers(columns);
        // No re-dimension allowed to the user
        ExpTable.getTableHeader().setResizingAllowed(false);
        // To fix width of collumns
        ExpTable.getColumnModel().getColumn(0).setPreferredWidth(25);
        ExpTable.getColumnModel().getColumn(1).setPreferredWidth(140);
        ExpTable.getColumnModel().getColumn(2).setPreferredWidth(80);
        ExpTable.getColumnModel().getColumn(3).setPreferredWidth(8);
        ExpTable.getColumnModel().getColumn(4).setPreferredWidth(122);
    }

    private void viewExperts() throws SQLException {

        ArrayList<Expert> ExpL = Exp.ExpertList();
        fillExpTable(ExpL);

    }

    private void viewExpertsCountry(String country) throws SQLException {

        ArrayList<Expert> ExpL = Exp.expertListByCountry(country);

        fillExpTable(ExpL);

    }

    public void viewSex() throws SQLException {

        String sex = SexText.getText();
        char SexSelec = sex.charAt(0);
        int num;
        num = Exp.ExpSex(sex);
        //if(buscadorSexo.getText().equals("F"))
        if (SexSelec == 'F') {
            Sexlabel.setText("There are " + num + " women in the DB");
        } else if (SexSelec == 'M') {
            Sexlabel.setText("There are " + num + " men in the db");
        }
        else {
            Sexlabel.setText("Incorrect character");
        }
        Sexlabel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ExpTable = new javax.swing.JTable();
        label1 = new java.awt.Label();
        CountrySelectList = new javax.swing.JComboBox<>();
        ViewCountryButton = new javax.swing.JButton();
        ViewAllButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SexText = new javax.swing.JTextField();
        CountButton = new javax.swing.JButton();
        Sexlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ExpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ExpTable);

        label1.setText("Select a Country::");

        CountrySelectList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EEUU", "Inglaterra", "España" }));

        ViewCountryButton.setText("View");
        ViewCountryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCountryButtonActionPerformed(evt);
            }
        });

        ViewAllButton.setText("View All");
        ViewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Sex:");

        SexText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexTextActionPerformed(evt);
            }
        });

        CountButton.setText("Count");
        CountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountButtonActionPerformed(evt);
            }
        });

        Sexlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SexText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(CountButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sexlabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CountrySelectList, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(ViewCountryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(ViewAllButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CountrySelectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewAllButton)
                        .addComponent(ViewCountryButton))
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SexText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CountButton)
                    .addComponent(Sexlabel))
                .addGap(43, 43, 43))
        );

        label1.getAccessibleContext().setAccessibleName("Select a Country:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllButtonActionPerformed
        // TODO add your handling code here:
        deleteExpertTable();

        try {

            viewExperts();

        } catch (SQLException ex) {
            Logger.getLogger(ExpertFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ViewAllButtonActionPerformed

    private void ViewCountryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCountryButtonActionPerformed
        // TODO add your handling code here:

        deleteExpertTable();

        try {

            viewExpertsCountry(CountrySelectList.getSelectedItem().toString());

        } catch (SQLException ex) {
            Logger.getLogger(ExpertFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ViewCountryButtonActionPerformed

    private void SexTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexTextActionPerformed

    private void CountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountButtonActionPerformed
        // TODO add your handling code here:
        try {
           // TODO add your handling code here:
           viewSex();
       } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, "Error at Count: "+ex.getMessage());
       }
    }//GEN-LAST:event_CountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpertFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CountButton;
    private javax.swing.JComboBox<String> CountrySelectList;
    private javax.swing.JTable ExpTable;
    private javax.swing.JTextField SexText;
    private javax.swing.JLabel Sexlabel;
    private javax.swing.JButton ViewAllButton;
    private javax.swing.JButton ViewCountryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
