/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business;

import Persistence.*;
import java.awt.Color;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class InsertCollab extends javax.swing.JFrame {

    //Declaramos las variables de la clase collaborates
    String codExp;
    String codCase;

    OracleConnection co = null;
    private CollaboratesManager Colab = null;
    private ExpertManager Exp = null;
    private PolicialcaseManager Pc = null;

    DefaultTableModel TExpertLook = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form InsertCollab
     */
    public InsertCollab() {
        initComponents();
    }

    public InsertCollab(OracleConnection co) throws SQLException {

        this.co=co;
        Colab = new CollaboratesManager(co);
        Exp = new ExpertManager(co);
        Pc= new PolicialcaseManager(co);
        initComponents();
        drawCollabTable();
        viewCollabs();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    private void drawCollabTable() {

        CollabTable.setModel(TExpertLook);
        String[] columnasTabla = {"CodExpert", "CodCaso", "DateC", "Description"};
        TExpertLook.setColumnIdentifiers(columnasTabla);
        // Para no permitir el redimensionamiento de las columnas con el ratón
        CollabTable.getTableHeader().setResizingAllowed(false);
        // Así se fija el ancho de las columnas
        CollabTable.getColumnModel().getColumn(0).setPreferredWidth(25);
        CollabTable.getColumnModel().getColumn(1).setPreferredWidth(140);
        CollabTable.getColumnModel().getColumn(2).setPreferredWidth(80);
        CollabTable.getColumnModel().getColumn(3).setPreferredWidth(122);
    }

    private void fillCollabTable(ArrayList<Collaborates> collab) {    //Cambiarlo para arraylsit de Collaborates
        Object[] column = new Object[4];
        int numRegistros = collab.size();

        for (int i = 0; i < numRegistros; i++) {
            column[0] = collab.get(i).getCodExperto();
            column[1] = collab.get(i).getCodCaso();
            column[2] = collab.get(i).getFecha();
            column[3] = collab.get(i).getDescripcionColaboracion();
            TExpertLook.addRow(column);
        }
    }

    private void deleteCollabTable() {

        int i = TExpertLook.getRowCount();
        while (TExpertLook.getRowCount() > 0) {
            TExpertLook.removeRow(0);
        }
    }

    private void viewCollabs() throws SQLException {

        ArrayList<Collaborates> ColabL = Colab.CollaboratesList();
        fillCollabTable(ColabL);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CollabTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CodExpTxt = new javax.swing.JTextField();
        CheckExpert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CodCaseTxt = new javax.swing.JTextField();
        CheckCase = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DateTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DescriptionTxt = new javax.swing.JTextField();
        InsertButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        expLabel = new javax.swing.JLabel();
        caseLabel = new javax.swing.JLabel();
        insertedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CollabTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(CollabTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CodExpert :");

        CodExpTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        CheckExpert.setText("Check");
        CheckExpert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckExpertActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CodCase :");

        CodCaseTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        CheckCase.setText("Check");
        CheckCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckCaseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Date :");

        DateTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Description");

        DescriptionTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        InsertButton.setText("Insert Collaboration");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(CodCaseTxt))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CodExpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckCase)
                                .addGap(18, 18, 18)
                                .addComponent(caseLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(InsertButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckExpert)
                                .addGap(18, 18, 18)
                                .addComponent(expLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(insertedLabel)
                                .addGap(47, 47, 47))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)
                        .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdateButton)
                        .addGap(30, 30, 30)))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CodExpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckExpert)
                            .addComponent(expLabel))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertedLabel)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodCaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckCase)
                    .addComponent(InsertButton)
                    .addComponent(caseLabel))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        // TODO add your handling code here:
         String ce = CodExpTxt.getText().trim();
         System.out.println(ce);
        String cc = CodCaseTxt.getText().trim();
        System.out.println(cc);
        String f = DateTxt.getText();
        String fe = DescriptionTxt.getText();
        
        Collaborates col = new Collaborates(ce, cc, f, fe);
        try {
            if(Colab.insertaColaboracion(col) == true){
                deleteCollabTable();
                viewCollabs();
                insertedLabel.setText("INSERTED");   
            }
            else{
                insertedLabel.setText("Non inserted");
            }
          
        } catch (SQLException ex) {
            insertedLabel.setText("ERROR SQL BUTTON");
            Logger.getLogger(InsertCollab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void CheckExpertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckExpertActionPerformed
        // TODO add your handling code here:
        codExp = CodExpTxt.getText();

        try {
            if (Exp.expertExists(codExp) == true) {  //If the expert does exist, a OK is shown (in green?)
                expLabel.setForeground(Color.blue);
                expLabel.setText("OK");

            } else {
                expLabel.setForeground(Color.RED);
                expLabel.setText("X");
                //Abrimos un nuevo frame para introducir el experto
                try {

                    InsertExpert iExp = new InsertExpert(co,codExp);
                    iExp.setVisible(true);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                } finally {
                    //this.dispose();           Cierra la ventana
                }
            
            }

        } catch (SQLException ex) {
            Logger.getLogger(InsertCollab.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_CheckExpertActionPerformed

    private void CheckCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckCaseActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            codCase = CodCaseTxt.getText();
            
            if(Pc.existeCaso(codCase) == true){
                caseLabel.setForeground(Color.blue);
                caseLabel.setText("OK");
            }
            else{
                
                caseLabel.setForeground(Color.RED);
                caseLabel.setText("X");
                
                try {
                    InsertCase nC = new InsertCase(co,codCase);
                    nC.setVisible(true);
                } catch (SQLException ex) {
                    caseLabel.setText("Error SQLException checkcase");
                    Logger.getLogger(InsertCollab.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        } catch (SQLException ex) {
             caseLabel.setText("Error SQLException 2 checkcase");
            Logger.getLogger(InsertCollab.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CheckCaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertCollab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertCollab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertCollab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertCollab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertCollab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckCase;
    private javax.swing.JButton CheckExpert;
    private javax.swing.JTextField CodCaseTxt;
    private javax.swing.JTextField CodExpTxt;
    private javax.swing.JTable CollabTable;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JTextField DescriptionTxt;
    private javax.swing.JButton InsertButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel caseLabel;
    private javax.swing.JLabel expLabel;
    private javax.swing.JLabel insertedLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
