/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business;
import Persistence.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    OracleConnection co = null;
    
    
    public MainFrame() {
        try {
            co=new OracleConnection();
            initComponents();
        } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error on main Window...: "+ex.getMessage());
                System.exit(1);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ExpManage = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        deleteCollab = new javax.swing.JMenu();
        InsertCollabButton = new javax.swing.JMenuItem();
        DeleteCollab = new javax.swing.JMenuItem();
        CollabManagement = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Database");

        jMenuItem2.setText("Connect");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Disconnect");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Experts");

        ExpManage.setText("Experts management");
        ExpManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpManageActionPerformed(evt);
            }
        });
        jMenu2.add(ExpManage);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Cases");

        jMenuItem5.setText("New Case");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        deleteCollab.setBorder(new javax.swing.border.MatteBorder(null));
        deleteCollab.setText("Collaborations");
        deleteCollab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCollabActionPerformed(evt);
            }
        });

        InsertCollabButton.setText("Insert");
        InsertCollabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertCollabButtonActionPerformed(evt);
            }
        });
        deleteCollab.add(InsertCollabButton);

        DeleteCollab.setText("Delete");
        DeleteCollab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCollabActionPerformed(evt);
            }
        });
        deleteCollab.add(DeleteCollab);

        CollabManagement.setText("Collaboration Management");
        CollabManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollabManagementActionPerformed(evt);
            }
        });
        deleteCollab.add(CollabManagement);

        jMenuBar1.add(deleteCollab);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        try {
            co = new OracleConnection();
            JOptionPane.showMessageDialog(null, "Connected");
            this.setVisible(true);
            
            
        }
        catch (Exception ex) {
        JOptionPane.showMessageDialog(null,ex.getStackTrace());
        
        
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
         try {
            co.disconnect();
            JOptionPane.showMessageDialog(null, "Disconnected");
            this.setVisible(true);
            
        }
        catch (Exception ex) {
        JOptionPane.showMessageDialog(null,ex.getStackTrace());
        
        
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    
    private void ExpManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpManageActionPerformed
        // TODO add your handling code here:
        try {
            
            ExpertFrame Ef = new ExpertFrame(co);
            Ef.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally
        {
            //this.dispose();           Cierra la ventana
        }
        
    }//GEN-LAST:event_ExpManageActionPerformed

    private void InsertCollabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertCollabButtonActionPerformed
        // TODO add your handling code here:
        try {
            
            InsertCollab Ic = new InsertCollab(co);
            Ic.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally
        {
            //this.dispose();           Cierra la ventana
        }
    }//GEN-LAST:event_InsertCollabButtonActionPerformed

    private void CollabManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollabManagementActionPerformed
        // TODO add your handling code here:
         try {
            
            CollabManageFrame Cmf = new CollabManageFrame(co);
            Cmf.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally
        {
            //this.dispose();
        }
        
    }//GEN-LAST:event_CollabManagementActionPerformed

    private void deleteCollabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCollabActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deleteCollabActionPerformed

    private void DeleteCollabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCollabActionPerformed
        // TODO add your handling code here:
         try {
            
            CollabDeleteFrame C = new CollabDeleteFrame(co);
            C.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally
        {
            //this.dispose();
        }
    }//GEN-LAST:event_DeleteCollabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CollabManagement;
    private javax.swing.JMenuItem DeleteCollab;
    private javax.swing.JMenuItem ExpManage;
    private javax.swing.JMenuItem InsertCollabButton;
    private javax.swing.JMenu deleteCollab;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
