/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Persistencia.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.*;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ignacio
 */
public class VentanaCasos extends javax.swing.JFrame {

    private static conexionOracle conn;
    private manejaCaso mCas;
    private DefaultTableModel modeloTCasos = new DefaultTableModel();
    
    /**
     * Creates new form VentanaCasos
     */
    public VentanaCasos(){
        
    }
    public VentanaCasos(conexionOracle c) throws SQLException {
        mCas = new manejaCaso(c);
        initComponents();
        dibujarTablaCasos();
        pideCasos();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    public void pideCasos() throws SQLException{
        ArrayList<caso> lCas = mCas.listaCasos();
        rellenarTablaCasos(lCas);
    }
    
    public void vaciarTablaCasos(){
        while(modeloTCasos.getRowCount() > 0)
            modeloTCasos.removeRow(0);
    }
    
    public void rellenarTablaCasos(ArrayList<caso> casos){
        Object[] columna = new Object[4];
        int numRegistros = casos.size();
        for (int i = 0; i < numRegistros; i++) 
        {
            columna[0] = casos.get(i).getCodCaso();
            columna[1] = casos.get(i).getNombre();
            columna[2] = casos.get(i).getFechaInicio();
            columna[3] = casos.get(i).getFechaFin();
            modeloTCasos.addRow(columna);
        }
    }
    
    public void dibujarTablaCasos() {
       
       jCaso.setModel(modeloTCasos);
       String[] columnasTabla = {"Código","Nombre","Fecha Inicio","Fecha Final"};
       modeloTCasos.setColumnIdentifiers(columnasTabla);
   
        jCaso.getTableHeader().setResizingAllowed(false);
    
        jCaso.getColumnModel().getColumn(0).setPreferredWidth(25);
        jCaso.getColumnModel().getColumn(1).setPreferredWidth(140);
        jCaso.getColumnModel().getColumn(2).setPreferredWidth(80);
        jCaso.getColumnModel().getColumn(3).setPreferredWidth(8);
        //jCaso.getColumnModel().getColumn(4).setPreferredWidth(122);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jCaso = new javax.swing.JTable();
        jTextTitulo = new javax.swing.JLabel();
        jBotonListar = new javax.swing.JButton();
        jBotonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCaso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jCaso);

        jTextTitulo.setText("Gestión de Casos");

        jBotonListar.setText("Listar Todo");
        jBotonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonListarActionPerformed(evt);
            }
        });

        jBotonBorrar.setText("Borrar Todo");
        jBotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jTextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBotonListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotonBorrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTextTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonListar)
                    .addComponent(jBotonBorrar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonListarActionPerformed
        try {
            this.vaciarTablaCasos();
            this.pideCasos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaExpertos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBotonListarActionPerformed

    private void jBotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBorrarActionPerformed
        vaciarTablaCasos();
    }//GEN-LAST:event_jBotonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCasos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonBorrar;
    private javax.swing.JButton jBotonListar;
    private javax.swing.JTable jCaso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTextTitulo;
    // End of variables declaration//GEN-END:variables
}
