/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;
import Persistencia.conexionOracle;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author IGNACIO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    static conexionOracle co = null;
    
    public VentanaPrincipal() {
        try {
            initComponents();
            
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            System.exit(1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Conexion = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        Expertos = new javax.swing.JMenu();
        GExpertos = new javax.swing.JMenuItem();
        CPoliciales = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Colaboraciones = new javax.swing.JMenu();
        GColaboraciones = new javax.swing.JMenuItem();
        GCompleta = new javax.swing.JMenu();
        GCompletaBD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Conexion.setText("Conexion");
        Conexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConexionActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Conectar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Conexion.add(jMenuItem1);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Conexion.add(Salir);

        jMenuBar1.add(Conexion);

        Expertos.setText("Expertos");
        Expertos.setToolTipText("");
        Expertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertosActionPerformed(evt);
            }
        });

        GExpertos.setText("Gestion de Expertos");
        GExpertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GExpertosActionPerformed(evt);
            }
        });
        Expertos.add(GExpertos);

        jMenuBar1.add(Expertos);

        CPoliciales.setText("Casos Policiales");

        jMenuItem2.setText("Gestión de Casos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        CPoliciales.add(jMenuItem2);

        jMenuBar1.add(CPoliciales);

        Colaboraciones.setText("Colaboraciones");

        GColaboraciones.setText("Gestión Colaboraciones");
        GColaboraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GColaboracionesActionPerformed(evt);
            }
        });
        Colaboraciones.add(GColaboraciones);

        jMenuBar1.add(Colaboraciones);

        GCompleta.setText("Gestión Completa");

        GCompletaBD.setText("Gestión Completa de la BD");
        GCompletaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCompletaBDActionPerformed(evt);
            }
        });
        GCompleta.add(GCompletaBD);

        jMenuBar1.add(GCompleta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//BORRAR ESTA MIERDA
    private void ExpertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertosActionPerformed
        try{ 
            VentanaExpertos vE = new VentanaExpertos(co);
            vE.setVisible(true);
            //vE.dibujarTablaExpertos();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_ExpertosActionPerformed
//BORRAR ESTA MIERDA
    private void ConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConexionActionPerformed

    }//GEN-LAST:event_ConexionActionPerformed
    //Acción correspondiente a Salir.
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        try {
           co.desconexion();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally
        {
            this.dispose();
        }
    }//GEN-LAST:event_SalirActionPerformed
    //Acción correspondiente a Gestión de Expertos
    //Tendría que haber creado la clase en minusculas.
    private void GExpertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GExpertosActionPerformed
        try
        {
           VentanaExpertos ex = new VentanaExpertos(co);
           ex.setVisible(true); 
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
      
    }//GEN-LAST:event_GExpertosActionPerformed

    private void GColaboracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GColaboracionesActionPerformed
        try{
            VentanaColaboraciones col = new VentanaColaboraciones(co);
            col.setVisible(true);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_GColaboracionesActionPerformed

    private void GCompletaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCompletaBDActionPerformed
        try{
            VentanaGCompleta gcom = new VentanaGCompleta(co);
            gcom.setVisible(true);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_GCompletaBDActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try{
            VentanaConectar gcon = new VentanaConectar(co);
            gcon.setVisible(true);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try{
            VentanaCasos gcas = new VentanaCasos(co);
            gcas.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CPoliciales;
    private javax.swing.JMenu Colaboraciones;
    private javax.swing.JMenu Conexion;
    private javax.swing.JMenu Expertos;
    private javax.swing.JMenuItem GColaboraciones;
    private javax.swing.JMenu GCompleta;
    private javax.swing.JMenuItem GCompletaBD;
    private javax.swing.JMenuItem GExpertos;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
