/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pila;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author usuario
 */
public class FramePila extends java.awt.Frame {

    /**
     * Creates new form FramePila
     */
    public FramePila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

                try {
                    
                    final int ancho=1000,alto=1000;
                    FramePila fp=new FramePila();
                    PilaCanvas Canvas=new PilaCanvas(ancho,alto,10);
                    fp.setSize(ancho,alto);
                    fp.add(Canvas);
                    fp.setVisible(true);
                    
                    PilaLenta p = new PilaLenta(10,Canvas);
                    
                    Productor prod1= new Productor(p,1);
                    Productor prod2= new Productor(p,2);
                    Thread c1 = new Thread (new Consumidor (p));
                    Thread c2 = new Thread (new Consumidor (p));
                    //Ponemos a correr los hilos
                    System.out.println("Comienza la main");
                    
                    prod1.start();
                    prod2.start();
                    c1.start();
                    c2.start();
                    
                    prod1.join();
                    prod2.join();
                    c1.join();
                    c2.join();
                    Thread.sleep(20000);
                    System.exit(0);
                } catch (InterruptedException ex) {
                    Logger.getLogger(FramePila.class.getName()).log(Level.SEVERE, null, ex);
                }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
