/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

//import static Aplicacion.aplicacionCliente.co;
import Persistencia.conexionOracle;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

        static conexionOracle co = null;
    /**
     * Creates new form ClienteFrame
     */
    public VentanaPrincipal() {
        
            try {
                co=new conexionOracle();
                initComponents();
            } catch (Exception ex) {
                //Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error en la ventana principal: "+ex.getMessage());
                System.exit(1);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenuPrincipal = new javax.swing.JMenuBar();
        Conexion = new javax.swing.JMenu();
        SubMenuConexionSalir = new javax.swing.JMenuItem();
        Expertos = new javax.swing.JMenu();
        SubMenuExpertosGestionExpertos = new javax.swing.JMenuItem();
        CasosPoliciales = new javax.swing.JMenu();
        Colaboraciones = new javax.swing.JMenu();
        SubMenuColaboracionesBuscarColaboraciones1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarraMenuPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BarraMenuPrincipal.setForeground(new java.awt.Color(255, 102, 102));

        Conexion.setBorder(null);
        Conexion.setText("Conexión");

        SubMenuConexionSalir.setText("Salir");
        SubMenuConexionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuConexionSalirActionPerformed(evt);
            }
        });
        Conexion.add(SubMenuConexionSalir);

        BarraMenuPrincipal.add(Conexion);

        Expertos.setText("Expertos");

        SubMenuExpertosGestionExpertos.setText("Gestión de Expertos");
        SubMenuExpertosGestionExpertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuExpertosGestionExpertosActionPerformed(evt);
            }
        });
        Expertos.add(SubMenuExpertosGestionExpertos);

        BarraMenuPrincipal.add(Expertos);

        CasosPoliciales.setText("Casos Policiales");
        BarraMenuPrincipal.add(CasosPoliciales);

        Colaboraciones.setText("Colaboraciones");

        SubMenuColaboracionesBuscarColaboraciones1.setText("Buscar Colaboradores");
        SubMenuColaboracionesBuscarColaboraciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuColaboracionesBuscarColaboraciones1ActionPerformed(evt);
            }
        });
        Colaboraciones.add(SubMenuColaboracionesBuscarColaboraciones1);

        BarraMenuPrincipal.add(Colaboraciones);

        setJMenuBar(BarraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenuColaboracionesBuscarColaboraciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuColaboracionesBuscarColaboraciones1ActionPerformed
        // TODO add your handling code here:
        try {
            ventanaColaboraciones vC = new ventanaColaboraciones(co);
            vC.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_SubMenuColaboracionesBuscarColaboraciones1ActionPerformed

    private void SubMenuExpertosGestionExpertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuExpertosGestionExpertosActionPerformed
        // TODO add your handling code here:

        try {
            ventanaExpertos vE = new ventanaExpertos(co);
            vE.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_SubMenuExpertosGestionExpertosActionPerformed

    private void SubMenuConexionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuConexionSalirActionPerformed
        // TODO add your handling code here:

        try {
            co.desconexion();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } finally {
            this.setVisible(false);//cierro la ventana
            this.dispose();//libero los recursos
        }

    }//GEN-LAST:event_SubMenuConexionSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenuPrincipal;
    private javax.swing.JMenu CasosPoliciales;
    private javax.swing.JMenu Colaboraciones;
    private javax.swing.JMenu Conexion;
    private javax.swing.JMenu Expertos;
    private javax.swing.JMenuItem SubMenuColaboracionesBuscarColaboraciones1;
    private javax.swing.JMenuItem SubMenuConexionSalir;
    private javax.swing.JMenuItem SubMenuExpertosGestionExpertos;
    // End of variables declaration//GEN-END:variables
}
