/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pila;

/**
 *
 * @author Pablo Cordon
 */
public class PilaFrame extends javax.swing.JFrame {

    /**
     * Creates new form PilaFrame
     */
    public PilaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
         
                    int alto = 800;
                    int ancho = 600;
                    PilaFrame f =  new PilaFrame();
                    //Tamaño de la ventana
                    f.setSize(alto, ancho);
                    //pila de tamaño 6
                    CanvasPila cv = new CanvasPila(ancho,alto,6);
                    PilaLenta pl = new PilaLenta(6,cv);
                    f.add(cv);
                    f.setVisible(true);
                    
                    //Creamos los hilos y los ponemos a correr.
                    
                    Productor p1 = new Productor (pl,1);
                    Productor p2 = new Productor (pl,2);
                    Productor p3 = new Productor (pl,3);
                    Productor p4 = new Productor (pl,4);
                    Consumidor c = new Consumidor(pl);
                    
                    p1.start();
                    p2.start();
                    p3.start();
                    p4.start();
                    c.start();
                    
                    p1.join();
                    p2.join();
                    p3.join();
                    p4.join();
                    c.join();
                    
                    Thread.sleep(20000);
                    System.exit(0);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
