(deffacts productos
(productos 

	(codigovendedor 001)
	(codigoproducto 010)	
	(pvpproducto 1.50))

(productos 
	(codigovendedor 002)
	(codigoproducto 010)	
	(pvpproducto 1.50))

(productos 
	(codigovendedor 002)
	(codigoproducto 013)	
	(pvpproducto 2.99))

(productos 
	(codigovendedor 001)
	(codigoproducto 013)	
	(pvpproducto 2.99))

(productos 
	(codigovendedor 003)
	(codigoproducto 015)	
	(pvpproducto 1.75))

(productos 
	(codigovendedor 003)
	(codigoproducto 016)	
	(pvpproducto 1.20))
)