
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class EjemploFrameAPP extends java.awt.Frame {

    /**
     * Creates new form EjemploFrameAPP
     */
    public EjemploFrameAPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.out.println("La app se cierra.....");
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
       
            
               
                    
                    int alto = 400;
                    int ancho = 600;
                    EjemploFrameAPP f =  new EjemploFrameAPP();
                    f.setSize(600, 400);
                    EjemploCanvas cv = new EjemploCanvas(ancho,alto);
                    f.add(cv);
                    f.setVisible(true);
                    
                    Recurso r = new Recurso(cv);
                    
                    Sumador h1=new Sumador (r,0);
                    Sumador h2=new Sumador (r,0);
                    Sumador h3=new Sumador (r,1);
                    
                    h1.start();
                    h2.start();
                    h3.start();
                    
                    h1.join();
                    h2.join();
                    h3.join();
                    
                    r.verContadores();
                    
                    Thread.sleep(3000);
                    
                    //System.exit(0);
                    
                    
                    
                
            
            
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
